### PR TITLE
Amend require for browserify compatibility.

### PR DESCRIPTION
**Pull request by kzc**
Similar fix to https://github.com/brianc/node-pg-types/commit/d240e961a36db90709ebf260d9d9cb1358e33e91

### CODE REVIEW

**Comment by kzc** [comment]
Regarding the failed pull request tests in Travis CI - I couldn't get the tests to work locally on unmodified source tree either.

**Comment by kzc** [comment]
@hoegaarden Any chance we can get this simple fix merged?

**Comment by ilikebits** [comment]
@hoegaarden Is there an ETA on this? This is a breaking bug for me -- see https://github.com/brianc/node-postgres/pull/875 and https://github.com/serverless/serverless/issues/201 and https://github.com/serverless/serverless-runtime-babel/issues/8.

**Comment by atwoodjw** [comment]
@ilikebits I was able to work around this temporarily by [shrinkwrapping](http://www.codedependant.net/2016/01/26/override-nested-dependencies-npm-3/).

**Comment by hoegaarden** [comment]
Sorry for the delay ... will try to push that into node-postgres asap.

**Comment by kzc** [comment]
@hoegaarden Could you please publish `pgpass@0.0.5` to npm?

https://www.npmjs.com/package/pgpass

**Comment by hoegaarden** [comment]
I just did so - also will issue a merge request for brianc/node-postgres in a sec.

**Comment by kzc** [comment]
Thanks

**Pull request merged**
